config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'

  resources :categories

  resources :product_attachments

  resources :products

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :product_categories
	has_many :products, through: :product_categories
end

app/models/concerns/permissions_concern.rb
module PermissionsConcern
	extend ActiveSupport::Concern

	def is_normal_user?
		self.permission_level >= 1
	end

	def is_admin_user?
		self.permission_level >= 2
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :product_attachments
	has_many :product_categories
	has_many :categories, through: :product_categories
	accepts_nested_attributes_for :product_attachments
	after_create :save_categories
	before_destroy :clear_categories

	def categories=(value)
		@categories = value
	end

	def save_categories
		unless @categories.nil?
			@categories.each do |category_id|
				ProductCategory.create(category_id: category_id, product_id: self.id)
			end
		end
	end

	def update_attachments(params)
      self.product_attachments.each(&:destroy) if self.product_attachments.present?
      params[:product_attachments]['image'].each do |image|
        self.product_attachments.create!(:image => image)
      end
    end

    def clear_categories
		unless @categories.nil?
	    	@categories.each do |id|
	    		ProductCategory.destroy(id)
	    	end
	    end
    end
end

app/models/product_attachment.rb
class ProductAttachment < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	belongs_to :product
	before_create :set_principal

	private

	def set_principal
		self.principal = true
	end
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	mount_uploader :avatar, AvatarUploader
	before_create :set_permission



	include PermissionsConcern

	private

	def set_permission
		self.permission_level = 1
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :lastname, :fono, :avatar, :email, :password, :password_confirmation])
		devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :lastname, :fono, :avatar, :email, :password, :password_confirmation, :current_password])
	end

	def authenticate_normal_user!
		redirect_to root_path user_signed_in? && current_user.is_normal_user?
	end

	def authenticate_admin!
		redirect_to root_path unless user_signed_in? && current_user.is_admin_user?
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show, :index] 

  respond_to :html

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/product_attachments_controller.rb
class ProductAttachmentsController < ApplicationController
  before_action :set_product_attachment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show, :index] 

  respond_to :html

  def index
    @product_attachments = ProductAttachment.all
    respond_with(@product_attachments)
  end

  def show
    respond_with(@product_attachment)
  end

  def new
    @product_attachment = ProductAttachment.new
    respond_with(@product_attachment)
  end

  def edit
  end

  def create
    @product_attachment = ProductAttachment.new(product_attachment_params)
    @product_attachment.save
    respond_with(@product_attachment)
  end

  def update
    if @product_attachment.update(product_attachment_params)
      respond_with(@product_attachment)
    end
  end

  def destroy
    @product_attachment.destroy
    respond_with(@product_attachment)
  end

  private
    def set_product_attachment
      @product_attachment = ProductAttachment.find(params[:id])
    end

    def product_attachment_params
      params.require(:product_attachment).permit(:product_id, :image, :principal)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show, :index] 

  respond_to :html

  def index
    @products = Product.paginate(page: params[:page], per_page: 6)
    respond_with(@products)
  end

  def show
    @product_attachments = @product.product_attachments.all
  end


  def new
    @product = Product.new
    @product_attachment = @product.product_attachments.build
    @categories = Category.all
  end

  def edit
    @product_attachment = @product.product_attachments.build
    @categories = Category.all
  end

  def create
    @product = Product.new(product_params)
    @product.categories = params[:categories]
    if @product.save
      params[:product_attachments]['image'].each do |i|
          @product_attachment = @product.product_attachments.create!(:image => i)
      end
      respond_with(@product)
    else
      format.html { render action: 'new' }
    end
  end

  def update
    @product.update_attachments(params) if params[:product_attachments]
    @product.update(product_params)
    update_categories
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :mini_description, :price, :discount, :categories, product_attachments_attributes: [:id, :product_id, :image])
    end

    def update_categories
      @cat = Category.all
      @newcategories = params[:categories]
      @cat.each do |c|
        #si no hay nuevas categorias
        if @newcategories.nil?
          #categorias existentes
          if @product.categories.include?(c)
            #si es una categoria que se tenia, pero no se quiere agregar, entonces se quita
            @dest = ProductCategory.where(:category_id => c.id, :product_id => @product.id).destroy_all
          end
        #si existe una nueva lista de categorias
        else
          #nuevas categorias
          if @newcategories.include?(c.id.to_s)
            #categorias existentes
            if @product.categories.include?(c)
              #si es una categoria que se quiere agregar y ademas existe (es decir, se quiere mantener), no se hace nada
            else
              #si es una categoria que se quiere agregar, pero no existe, entonces se agrega
              ProductCategory.create(category_id: c.id, product_id: @product.id)
            end
          #categorias que no se quieren agregar
          else
            #categorias existentes
            if @product.categories.include?(c)
              #si es una categoria que se tenia, pero no se quiere agregar, entonces se quita
              @dest = ProductCategory.where(:category_id => c.id, :product_id => @product.id).destroy_all
            end
          end
        end
      end
    end

    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/product_attachments_helper.rb
module ProductAttachmentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @category.name %></h1>
<div class="categ-descript">
	<%= @category.description %>
</div>

<ul class="products">
	<% @category.products.order("created_at asc").each do |product| %>
		<li class="product">
      		<div class="txt-center">
        		<h3><%= link_to product.name, product, :class=>"without-underline" %></h3>
        		<p><%= link_to image_tag(product.product_attachments.where(:principal => true).first.image_url(:mini), :class => "images"), product %></p>
        		<p><%= product.mini_description %></p>
       			<p class="prices" >Consultar</p>
		      <% if user_signed_in? && current_user.is_admin_user? %>
		        <p><%= link_to 'Editar', edit_product_path(product) %></p>
		        <p><%= link_to 'Borrar', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
		      <% end %>
        	</div>
		</li>
	<% end %>

</ul>

<% if user_signed_in? && current_user.is_admin_user? %>
	<%= link_to 'Edit', edit_category_path(@category) %> |
	<%= link_to 'Volver', categories_path, :class=>"without-underline" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tecnokits</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="woocommerce-page">

	<%= render "partials/mainbar" %>

	<%= render "partials/navigation" %>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<% if user_signed_in? %>
		<%= render "partials/navuser" %>
	<% end %>


	<div id="container" style="margin:0 auto;">
		<%= yield %>
	</div>

	<%= render "partials/footbar" %>
</body>

</html>

app/views/partials/_footbar.html.erb
<footer class="footer navbar-fixed-bottom">
	<ul class="row large-padding">
		<li class="col-md">
			Sobre nosotros
		</li>
		<li class="col-md">
			Contáctanos
		</li>
		<li class="col-md">
			Todos los derechos reservados
		</li>
	</ul>
</footer>

app/views/partials/_mainbar.html.erb
<header>
	<div id="main-nav" class="navbar navbar-inverse">
		<ul class="row large-padding">
			<li class="col-md-8">
				<%= image_tag("http://res.cloudinary.com/dnq7udia2/image/upload/v1470151018/tecnokits3_wgnpc5.png") %>
			</li>
			<li class="col-md">
				
			</li>
		</ul>
	</div>
</header>

app/views/partials/_navigation.html.erb
<header>
	<ul class="row large-padding navigation-bar-text">
		<li id="top-nav" class="col-md-2 navigation-bar navigation-background">
			<%= link_to "Principal", root_path %>
		</li>
		<li id="top-nav" class="col-md-2 navigation-bar navigation-background">
			<%= link_to "Kits", controller: "/categories", action: "show", id: "1" %>
		</li>
		<li id="top-nav" class="col-md-2 navigation-bar navigation-background">
			<%= link_to "Robótica", controller: "/categories", action: "show", id: "2" %>
		</li>
		<li id="top-nav" class="col-md-2 navigation-bar navigation-background">
			<%= link_to "Arduino", controller: "/categories", action: "show", id: "3" %>
		</li>
	</ul>
</header>

app/views/partials/_navuser.html.erb
<header>
	<div class="row large-padding">
		<div class="col-md-9">
			<%= link_to "Editar Cuenta", edit_user_registration_path %>
		</div>
		<div class="col-md">
			<%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
		</div>
	</div>
</header>

app/views/product_attachments/_form.html.erb
<%= image_tag @product_attachment.image_url %>

<%= form_for(@product_attachment) do |f| %>
  <% if @product_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_attachment.errors.count, "error") %> prohibited this product_attachment from being saved:</h2>

      <ul>
      <% @product_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :principal %><br>
    <%= f.check_box :principal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_attachments/edit.html.erb
<h1>Editing product_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_attachment %> |
<%= link_to 'Back', product_attachments_path %>

app/views/product_attachments/index.html.erb
<h1>Listing product_attachments</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Image</th>
      <th>Principal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_attachments.each do |product_attachment| %>
      <tr>
        <td><%= product_attachment.product_id %></td>
        <td><%= product_attachment.image %></td>
        <td><%= product_attachment.principal %></td>
        <td><%= link_to 'Show', product_attachment %></td>
        <td><%= link_to 'Edit', edit_product_attachment_path(product_attachment) %></td>
        <td><%= link_to 'Destroy', product_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product attachment', new_product_attachment_path %>

app/views/product_attachments/new.html.erb
<h1>New product_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', product_attachments_path %>

app/views/product_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_attachment.product_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product_attachment.image %>
</p>

<p>
  <strong>Principal:</strong>
  <%= @product_attachment.principal %>
</p>

<%= link_to 'Edit', edit_product_attachment_path(@product_attachment) %> |
<%= link_to 'Back', product_attachments_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :mini_description %><br>
    <%= f.text_area :mini_description %>
  </div>
  <div class="field">
    <label>Categorias</label>
    <% @categories.each do |category| %>
      <div>
        <%= check_box_tag "categories[]", category.id, @product.categories.include?(category) %> <%= category.name %>
      </div>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.number_field :discount %>
  </div>
  <%= f.fields_for :product_attachments do |p| %>
     <div class="field">
       <%= p.label :image %><br>
       <%= p.file_field :image, :multiple => true, name: "product_attachments[image][]" %>
     </div>
   <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Productos</h1>
<ul class="products">
  <% @products.each do |product| %>
    <li class="product">
      <div class="txt-center">
        <h3><%= link_to product.name, product, :class=>"without-underline" %></h3>
        <% unless product.product_attachments.where(:principal => true).first.nil? %>
          <p><%= link_to image_tag(product.product_attachments.where(:principal => true).first.image_url(:mini)), product %></p>
        <% end %>        
        <p><%= product.mini_description %></p>
        <p class="prices" ><%= number_to_currency(product.price, :delimiter => '.', precision: 0) %></p>
      </div>
      <div>
      <p>Categorías</p>
        <% product.categories.each do |category| %>
          <p>
            <%= link_to category.name, category %>
          </p>
        <% end %>
      </div>
      <% if user_signed_in? && current_user.is_admin_user? %>
        <p><%= link_to 'Editar', edit_product_path(product) %></p>
        <p><%= link_to 'Borrar', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      <% end %>
    </li>
  <% end %>
</ul>



<br>

<%= will_paginate @products %>

<% if user_signed_in? && current_user.is_admin_user? %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="product">
  <div class="images">
    <div class="secondary-image">
      <% @product_attachments.each do |p| %>
      <p>
        <%= image_tag p.image_url(:thumb) %>
      </p>
      <% if user_signed_in? && current_user.is_admin_user? %>
        <%= link_to "Editar imagenes", edit_product_attachment_path(p) %>
      <% end %>
    <% end %>
    </div>
    <div>
      <%= image_tag(@product.product_attachments.where(:principal => true).first.image_url, :class=>"principal-image") %>
    </div>

  </div>
  <div class="entry-summary"> 
    <h1> <%= @product.name %> </h1>
    <p><%= @product.description %></p>
    <p class="prices" >Consultar</p>

    <div>
      <p>Categorías 
      <% @product.categories.each do |category| %>
          <%= link_to category.name, category %> 
        </p>
      <% end %>
    </div>
  </div>
 
</div>


<% if user_signed_in? && current_user.is_admin_user? %>
  <%= link_to 'Editar', edit_product_path(@product) %> |
  <%= link_to 'Volver', products_path %>
<% end %>

app/views/welcome/index.html.erb
<h1>Bienvenido</h1>

	<% if user_signed_in? %>
	<p>Hola <%= current_user.username%>, tus datos son:</p>
	<p>Apellido: <%= current_user.email%></p>
	<p>Nombre: <%= current_user.name%></p>
	<p>Apellido: <%= current_user.lastname%></p>
	<p>Fono: <%= current_user.fono%></p>
	<p>Permission_level: <%= current_user.permission_level%></p>
	<p>Avatar: <%= image_tag current_user.avatar_url(:mini) %></p>
	<% end %>

<div class="principal">
	<div class="datos">
		<div class="title">
			Nuestro objetivo
		</div>
		<div class="info">
			<img src="http://res.cloudinary.com/clupin/image/upload/v1471653922/1_dnztvu.jpg", class="image">
			<p>Buscamos acercar el uso de la tecnología y herramientas tecnológicas a los estudiantes y sus profesores. Frente a la búsqueda de material relacionado para mi labor docente, me encontré con que la información está en la web, no siempre correcta, no siempre ordenado, no en nuestro idioma, no siempre enfocada en educación, la  mayoría de las veces la programación en códigos difíciles de trabajar y entender. Es por esto que me planteé como objetivo elaborar una serie de proyectos enfocados en educación con el uso de estos recursos, decidimos buscar y adaptar un programa para acercar la programación a los estudiantes, así llegamos a nuestro editor gráfico de Arduino basado en bloques, como siempre hemos dicho: <i>“Es programar, utilizando bloques como legos”</i>. </p>
		</div>
	</div>
	<div class="datos">
		<div class="title">
			Programar con bloques
		</div>
		<div class="info">
			<img src="http://res.cloudinary.com/clupin/image/upload/v1471653925/2_n4tkxq.png", class="image">
			<p>Es desarrollar programas con instrucciones y acciones, utilizando diversos bloques prediseñados, los cuales representan un código determinado, al ir uniendo o enlazando estos bloques entre sí, se va generando el programa, el cual también podremos ver como código en línea de comandos.
 </p>
		</div>
	</div>
	<div class="datos">
		<div class="title">
			¿Qué es Arduino?
		</div>
		<div class="info">
			<img src="http://res.cloudinary.com/clupin/image/upload/v1471653924/3_qeenb9.jpg", class="image">
			<p>Arduino es una plataforma de prototipos electrónica basada en software y hardware flexible y fácil de usar.</p>
      		<p>Arduino puede sentir el entorno por medio de la recepción de entradas desde una variedad de sensores y puede afectar a su alrededor mediante el control de luces, motores, pantallas y otros artefactos. </p>
		</div>
	</div>
	<div class="datos">
		<div class="title">
			¿Qué es blockly@TecnoKits?
		</div>
		<div class="info">
			<img src="http://res.cloudinary.com/clupin/image/upload/v1471653924/4_i2iu7v.png", class="image">
			<p>Es un programa web para la programación gráfica de Arduino y su traducción a código. </p>
			<p>Se basa en Blockly, un programa de edición gráfica con una interfaz web. Proporciona un único tipo de traducción de la programación gráfica, para generar código para copiar y pegar en el IDE de Arduino.</p>
			<p>En el caso particular de Blockly@TecnoKits es una adaptación y traducción de Blocklyarduino, en la cual hemos incluido los bloques necesarios para trabajar en nuestros proyectos.</p>
		</div>
	</div>
</div>